
################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, QSize, Qt
from PySide6.QtGui import QAction
from PySide6.QtWidgets import (
    QDockWidget,
    QHBoxLayout,
    QMainWindow,
    QMenu,
    QMenuBar,
    QSizePolicy,
    QStatusBar,
    QToolBar,
    QWidget,
)


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowNestedDocks|QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.actionNewSession = QAction(MainWindow)
        self.actionNewSession.setObjectName("actionNewSession")
        self.actionOpenSession = QAction(MainWindow)
        self.actionOpenSession.setObjectName("actionOpenSession")
        self.actionSaveSession = QAction(MainWindow)
        self.actionSaveSession.setObjectName("actionSaveSession")
        self.actionLoadData = QAction(MainWindow)
        self.actionLoadData.setObjectName("actionLoadData")
        self.actionExportData = QAction(MainWindow)
        self.actionExportData.setObjectName("actionExportData")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionUndo.setEnabled(False)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionRedo.setEnabled(False)
        self.actionFindSeries = QAction(MainWindow)
        self.actionFindSeries.setObjectName("actionFindSeries")
        self.actionRefreshData = QAction(MainWindow)
        self.actionRefreshData.setObjectName("actionRefreshData")
        self.actionFullscreen = QAction(MainWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionThemeLight = QAction(MainWindow)
        self.actionThemeLight.setObjectName("actionThemeLight")
        self.actionThemeDark = QAction(MainWindow)
        self.actionThemeDark.setObjectName("actionThemeDark")
        self.actionThemeAuto = QAction(MainWindow)
        self.actionThemeAuto.setObjectName("actionThemeAuto")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionContextualHelp = QAction(MainWindow)
        self.actionContextualHelp.setObjectName("actionContextualHelp")
        self.actionKeyboardShortcuts = QAction(MainWindow)
        self.actionKeyboardShortcuts.setObjectName("actionKeyboardShortcuts")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.centralLayout = QHBoxLayout(self.centralWidget)
        self.centralLayout.setObjectName("centralLayout")
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.vizPanelPlaceholder = QWidget(self.centralWidget)
        self.vizPanelPlaceholder.setObjectName("vizPanelPlaceholder")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.vizPanelPlaceholder.sizePolicy().hasHeightForWidth())
        self.vizPanelPlaceholder.setSizePolicy(sizePolicy)

        self.centralLayout.addWidget(self.vizPanelPlaceholder)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName("menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1400, 22))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuPanels = QMenu(self.menuView)
        self.menuPanels.setObjectName("menuPanels")
        self.menuTheme = QMenu(self.menuView)
        self.menuTheme.setObjectName("menuTheme")
        self.menuTools = QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        self.mainToolBar.setMovable(True)
        self.mainToolBar.setIconSize(QSize(24, 24))
        self.mainToolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.mainToolBar)
        self.dataDock = QDockWidget(MainWindow)
        self.dataDock.setObjectName("dataDock")
        self.dataDock.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetMovable|QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.dataPanelPlaceholder = QWidget()
        self.dataPanelPlaceholder.setObjectName("dataPanelPlaceholder")
        self.dataPanelPlaceholder.setMinimumSize(QSize(250, 0))
        self.dataDock.setWidget(self.dataPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dataDock)
        self.configDock = QDockWidget(MainWindow)
        self.configDock.setObjectName("configDock")
        self.configDock.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetMovable|QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.configPanelPlaceholder = QWidget()
        self.configPanelPlaceholder.setObjectName("configPanelPlaceholder")
        self.configPanelPlaceholder.setMinimumSize(QSize(280, 0))
        self.configDock.setWidget(self.configPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.configDock)
        self.operationsDock = QDockWidget(MainWindow)
        self.operationsDock.setObjectName("operationsDock")
        self.operationsDock.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetMovable|QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.operationsPanelPlaceholder = QWidget()
        self.operationsPanelPlaceholder.setObjectName("operationsPanelPlaceholder")
        self.operationsPanelPlaceholder.setMinimumSize(QSize(280, 0))
        self.operationsDock.setWidget(self.operationsPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.operationsDock)
        self.streamingDock = QDockWidget(MainWindow)
        self.streamingDock.setObjectName("streamingDock")
        self.streamingDock.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetMovable|QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.streamingPanelPlaceholder = QWidget()
        self.streamingPanelPlaceholder.setObjectName("streamingPanelPlaceholder")
        self.streamingPanelPlaceholder.setMaximumSize(QSize(16777215, 150))
        self.streamingDock.setWidget(self.streamingPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.streamingDock)
        self.resultsDock = QDockWidget(MainWindow)
        self.resultsDock.setObjectName("resultsDock")
        self.resultsDock.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetMovable|QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.resultsPanelPlaceholder = QWidget()
        self.resultsPanelPlaceholder.setObjectName("resultsPanelPlaceholder")
        self.resultsPanelPlaceholder.setMaximumSize(QSize(16777215, 200))
        self.resultsDock.setWidget(self.resultsPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.resultsDock)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNewSession)
        self.menuFile.addAction(self.actionOpenSession)
        self.menuFile.addAction(self.actionSaveSession)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoadData)
        self.menuFile.addAction(self.actionExportData)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFindSeries)
        self.menuView.addAction(self.menuPanels.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRefreshData)
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menuTheme.addAction(self.actionThemeLight)
        self.menuTheme.addAction(self.actionThemeDark)
        self.menuTheme.addAction(self.actionThemeAuto)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionContextualHelp)
        self.menuHelp.addAction(self.actionKeyboardShortcuts)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.mainToolBar.addAction(self.actionLoadData)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionNewSession)
        self.mainToolBar.addAction(self.actionSaveSession)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", "Platform Base v2.0 - Time Series Analysis", None))
        self.actionNewSession.setText(QCoreApplication.translate("MainWindow", "&New Session", None))
#if QT_CONFIG(tooltip)
        self.actionNewSession.setToolTip(QCoreApplication.translate("MainWindow", "Create a new session (Ctrl+N)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNewSession.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenSession.setText(QCoreApplication.translate("MainWindow", "&Open Session...", None))
#if QT_CONFIG(tooltip)
        self.actionOpenSession.setToolTip(QCoreApplication.translate("MainWindow", "Open an existing session (Ctrl+O)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenSession.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveSession.setText(QCoreApplication.translate("MainWindow", "&Save Session...", None))
#if QT_CONFIG(tooltip)
        self.actionSaveSession.setToolTip(QCoreApplication.translate("MainWindow", "Save current session (Ctrl+S)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSaveSession.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoadData.setText(QCoreApplication.translate("MainWindow", "&Load Data...", None))
#if QT_CONFIG(tooltip)
        self.actionLoadData.setToolTip(QCoreApplication.translate("MainWindow", "Load data from file (Ctrl+L)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionLoadData.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionExportData.setText(QCoreApplication.translate("MainWindow", "&Export Data...", None))
#if QT_CONFIG(tooltip)
        self.actionExportData.setToolTip(QCoreApplication.translate("MainWindow", "Export data to file (Ctrl+E)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExportData.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", "E&xit", None))
#if QT_CONFIG(tooltip)
        self.actionExit.setToolTip(QCoreApplication.translate("MainWindow", "Exit application (Ctrl+Q)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", "&Undo", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", "Undo last operation (Ctrl+Z)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", "&Redo", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", "Redo last undone operation (Ctrl+Y)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionFindSeries.setText(QCoreApplication.translate("MainWindow", "&Find Series...", None))
#if QT_CONFIG(tooltip)
        self.actionFindSeries.setToolTip(QCoreApplication.translate("MainWindow", "Find/filter series (Ctrl+F)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFindSeries.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionRefreshData.setText(QCoreApplication.translate("MainWindow", "&Refresh Data", None))
#if QT_CONFIG(tooltip)
        self.actionRefreshData.setToolTip(QCoreApplication.translate("MainWindow", "Refresh/reload current data (F5)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRefreshData.setShortcut(QCoreApplication.translate("MainWindow", "F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionFullscreen.setText(QCoreApplication.translate("MainWindow", "&Fullscreen", None))
#if QT_CONFIG(tooltip)
        self.actionFullscreen.setToolTip(QCoreApplication.translate("MainWindow", "Toggle fullscreen mode (F11)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFullscreen.setShortcut(QCoreApplication.translate("MainWindow", "F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionThemeLight.setText(QCoreApplication.translate("MainWindow", "Light Theme", None))
#if QT_CONFIG(tooltip)
        self.actionThemeLight.setToolTip(QCoreApplication.translate("MainWindow", "Switch to light theme", None))
#endif // QT_CONFIG(tooltip)
        self.actionThemeDark.setText(QCoreApplication.translate("MainWindow", "Dark Theme", None))
#if QT_CONFIG(tooltip)
        self.actionThemeDark.setToolTip(QCoreApplication.translate("MainWindow", "Switch to dark theme", None))
#endif // QT_CONFIG(tooltip)
        self.actionThemeAuto.setText(QCoreApplication.translate("MainWindow", "Auto Theme", None))
#if QT_CONFIG(tooltip)
        self.actionThemeAuto.setToolTip(QCoreApplication.translate("MainWindow", "Use system theme", None))
#endif // QT_CONFIG(tooltip)
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", "&Settings...", None))
#if QT_CONFIG(tooltip)
        self.actionSettings.setToolTip(QCoreApplication.translate("MainWindow", "Application settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionContextualHelp.setText(QCoreApplication.translate("MainWindow", "&Contextual Help", None))
#if QT_CONFIG(tooltip)
        self.actionContextualHelp.setToolTip(QCoreApplication.translate("MainWindow", "Show help for current context (F1)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionContextualHelp.setShortcut(QCoreApplication.translate("MainWindow", "F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionKeyboardShortcuts.setText(QCoreApplication.translate("MainWindow", "&Keyboard Shortcuts", None))
#if QT_CONFIG(tooltip)
        self.actionKeyboardShortcuts.setToolTip(QCoreApplication.translate("MainWindow", "Show all keyboard shortcuts", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionKeyboardShortcuts.setShortcut(QCoreApplication.translate("MainWindow", "Ctrl+?", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", "&About...", None))
#if QT_CONFIG(tooltip)
        self.actionAbout.setToolTip(QCoreApplication.translate("MainWindow", "About Platform Base", None))
#endif // QT_CONFIG(tooltip)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", "&File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", "&Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", "&View", None))
        self.menuPanels.setTitle(QCoreApplication.translate("MainWindow", "Panels", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", "Theme", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", "&Tools", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", "&Help", None))
        self.mainToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", "Main", None))
        self.dataDock.setWindowTitle(QCoreApplication.translate("MainWindow", "Data Panel", None))
        self.configDock.setWindowTitle(QCoreApplication.translate("MainWindow", "Configuration", None))
        self.operationsDock.setWindowTitle(QCoreApplication.translate("MainWindow", "Operations", None))
        self.streamingDock.setWindowTitle(QCoreApplication.translate("MainWindow", "Streaming Controls", None))
        self.resultsDock.setWindowTitle(QCoreApplication.translate("MainWindow", "Results", None))
    # retranslateUi

