# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QHBoxLayout, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QMainWindow.AllowNestedDocks|QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.actionNewSession = QAction(MainWindow)
        self.actionNewSession.setObjectName(u"actionNewSession")
        self.actionOpenSession = QAction(MainWindow)
        self.actionOpenSession.setObjectName(u"actionOpenSession")
        self.actionSaveSession = QAction(MainWindow)
        self.actionSaveSession.setObjectName(u"actionSaveSession")
        self.actionLoadData = QAction(MainWindow)
        self.actionLoadData.setObjectName(u"actionLoadData")
        self.actionExportData = QAction(MainWindow)
        self.actionExportData.setObjectName(u"actionExportData")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionUndo.setEnabled(False)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionRedo.setEnabled(False)
        self.actionFindSeries = QAction(MainWindow)
        self.actionFindSeries.setObjectName(u"actionFindSeries")
        self.actionRefreshData = QAction(MainWindow)
        self.actionRefreshData.setObjectName(u"actionRefreshData")
        self.actionFullscreen = QAction(MainWindow)
        self.actionFullscreen.setObjectName(u"actionFullscreen")
        self.actionThemeLight = QAction(MainWindow)
        self.actionThemeLight.setObjectName(u"actionThemeLight")
        self.actionThemeDark = QAction(MainWindow)
        self.actionThemeDark.setObjectName(u"actionThemeDark")
        self.actionThemeAuto = QAction(MainWindow)
        self.actionThemeAuto.setObjectName(u"actionThemeAuto")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionContextualHelp = QAction(MainWindow)
        self.actionContextualHelp.setObjectName(u"actionContextualHelp")
        self.actionKeyboardShortcuts = QAction(MainWindow)
        self.actionKeyboardShortcuts.setObjectName(u"actionKeyboardShortcuts")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.centralLayout = QHBoxLayout(self.centralWidget)
        self.centralLayout.setObjectName(u"centralLayout")
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.vizPanelPlaceholder = QWidget(self.centralWidget)
        self.vizPanelPlaceholder.setObjectName(u"vizPanelPlaceholder")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.vizPanelPlaceholder.sizePolicy().hasHeightForWidth())
        self.vizPanelPlaceholder.setSizePolicy(sizePolicy)

        self.centralLayout.addWidget(self.vizPanelPlaceholder)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1400, 22))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuPanels = QMenu(self.menuView)
        self.menuPanels.setObjectName(u"menuPanels")
        self.menuTheme = QMenu(self.menuView)
        self.menuTheme.setObjectName(u"menuTheme")
        self.menuTools = QMenu(self.menuBar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QToolBar(MainWindow)
        self.mainToolBar.setObjectName(u"mainToolBar")
        self.mainToolBar.setMovable(True)
        self.mainToolBar.setIconSize(QSize(24, 24))
        self.mainToolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.mainToolBar)
        self.dataDock = QDockWidget(MainWindow)
        self.dataDock.setObjectName(u"dataDock")
        self.dataPanelPlaceholder = QWidget()
        self.dataPanelPlaceholder.setObjectName(u"dataPanelPlaceholder")
        self.dataPanelPlaceholder.setMinimumSize(QSize(250, 0))
        self.dataDock.setWidget(self.dataPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dataDock)
        self.configDock = QDockWidget(MainWindow)
        self.configDock.setObjectName(u"configDock")
        self.configPanelPlaceholder = QWidget()
        self.configPanelPlaceholder.setObjectName(u"configPanelPlaceholder")
        self.configPanelPlaceholder.setMinimumSize(QSize(280, 0))
        self.configDock.setWidget(self.configPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.configDock)
        self.operationsDock = QDockWidget(MainWindow)
        self.operationsDock.setObjectName(u"operationsDock")
        self.operationsPanelPlaceholder = QWidget()
        self.operationsPanelPlaceholder.setObjectName(u"operationsPanelPlaceholder")
        self.operationsPanelPlaceholder.setMinimumSize(QSize(280, 0))
        self.operationsDock.setWidget(self.operationsPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.operationsDock)
        self.streamingDock = QDockWidget(MainWindow)
        self.streamingDock.setObjectName(u"streamingDock")
        self.streamingPanelPlaceholder = QWidget()
        self.streamingPanelPlaceholder.setObjectName(u"streamingPanelPlaceholder")
        self.streamingPanelPlaceholder.setMaximumSize(QSize(16777215, 150))
        self.streamingDock.setWidget(self.streamingPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.streamingDock)
        self.resultsDock = QDockWidget(MainWindow)
        self.resultsDock.setObjectName(u"resultsDock")
        self.resultsPanelPlaceholder = QWidget()
        self.resultsPanelPlaceholder.setObjectName(u"resultsPanelPlaceholder")
        self.resultsPanelPlaceholder.setMaximumSize(QSize(16777215, 200))
        self.resultsDock.setWidget(self.resultsPanelPlaceholder)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.resultsDock)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNewSession)
        self.menuFile.addAction(self.actionOpenSession)
        self.menuFile.addAction(self.actionSaveSession)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoadData)
        self.menuFile.addAction(self.actionExportData)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFindSeries)
        self.menuView.addAction(self.menuPanels.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRefreshData)
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menuTheme.addAction(self.actionThemeLight)
        self.menuTheme.addAction(self.actionThemeDark)
        self.menuTheme.addAction(self.actionThemeAuto)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionContextualHelp)
        self.menuHelp.addAction(self.actionKeyboardShortcuts)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.mainToolBar.addAction(self.actionLoadData)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionNewSession)
        self.mainToolBar.addAction(self.actionSaveSession)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Platform Base v2.0 - Time Series Analysis", None))
        self.actionNewSession.setText(QCoreApplication.translate("MainWindow", u"&New Session", None))
#if QT_CONFIG(tooltip)
        self.actionNewSession.setToolTip(QCoreApplication.translate("MainWindow", u"Create a new session (Ctrl+N)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNewSession.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenSession.setText(QCoreApplication.translate("MainWindow", u"&Open Session...", None))
#if QT_CONFIG(tooltip)
        self.actionOpenSession.setToolTip(QCoreApplication.translate("MainWindow", u"Open an existing session (Ctrl+O)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenSession.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveSession.setText(QCoreApplication.translate("MainWindow", u"&Save Session...", None))
#if QT_CONFIG(tooltip)
        self.actionSaveSession.setToolTip(QCoreApplication.translate("MainWindow", u"Save current session (Ctrl+S)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSaveSession.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoadData.setText(QCoreApplication.translate("MainWindow", u"&Load Data...", None))
#if QT_CONFIG(tooltip)
        self.actionLoadData.setToolTip(QCoreApplication.translate("MainWindow", u"Load data from file (Ctrl+L)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionLoadData.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionExportData.setText(QCoreApplication.translate("MainWindow", u"&Export Data...", None))
#if QT_CONFIG(tooltip)
        self.actionExportData.setToolTip(QCoreApplication.translate("MainWindow", u"Export data to file (Ctrl+E)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExportData.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"E&xit", None))
#if QT_CONFIG(tooltip)
        self.actionExit.setToolTip(QCoreApplication.translate("MainWindow", u"Exit application (Ctrl+Q)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"&Undo", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo last operation (Ctrl+Z)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"&Redo", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", u"Redo last undone operation (Ctrl+Y)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionFindSeries.setText(QCoreApplication.translate("MainWindow", u"&Find Series...", None))
#if QT_CONFIG(tooltip)
        self.actionFindSeries.setToolTip(QCoreApplication.translate("MainWindow", u"Find/filter series (Ctrl+F)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFindSeries.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionRefreshData.setText(QCoreApplication.translate("MainWindow", u"&Refresh Data", None))
#if QT_CONFIG(tooltip)
        self.actionRefreshData.setToolTip(QCoreApplication.translate("MainWindow", u"Refresh/reload current data (F5)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRefreshData.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionFullscreen.setText(QCoreApplication.translate("MainWindow", u"&Fullscreen", None))
#if QT_CONFIG(tooltip)
        self.actionFullscreen.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle fullscreen mode (F11)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFullscreen.setShortcut(QCoreApplication.translate("MainWindow", u"F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionThemeLight.setText(QCoreApplication.translate("MainWindow", u"Light Theme", None))
#if QT_CONFIG(tooltip)
        self.actionThemeLight.setToolTip(QCoreApplication.translate("MainWindow", u"Switch to light theme", None))
#endif // QT_CONFIG(tooltip)
        self.actionThemeDark.setText(QCoreApplication.translate("MainWindow", u"Dark Theme", None))
#if QT_CONFIG(tooltip)
        self.actionThemeDark.setToolTip(QCoreApplication.translate("MainWindow", u"Switch to dark theme", None))
#endif // QT_CONFIG(tooltip)
        self.actionThemeAuto.setText(QCoreApplication.translate("MainWindow", u"Auto Theme", None))
#if QT_CONFIG(tooltip)
        self.actionThemeAuto.setToolTip(QCoreApplication.translate("MainWindow", u"Use system theme", None))
#endif // QT_CONFIG(tooltip)
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"&Settings...", None))
#if QT_CONFIG(tooltip)
        self.actionSettings.setToolTip(QCoreApplication.translate("MainWindow", u"Application settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionContextualHelp.setText(QCoreApplication.translate("MainWindow", u"&Contextual Help", None))
#if QT_CONFIG(tooltip)
        self.actionContextualHelp.setToolTip(QCoreApplication.translate("MainWindow", u"Show help for current context (F1)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionContextualHelp.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionKeyboardShortcuts.setText(QCoreApplication.translate("MainWindow", u"&Keyboard Shortcuts", None))
#if QT_CONFIG(tooltip)
        self.actionKeyboardShortcuts.setToolTip(QCoreApplication.translate("MainWindow", u"Show all keyboard shortcuts", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionKeyboardShortcuts.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+?", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"&About...", None))
#if QT_CONFIG(tooltip)
        self.actionAbout.setToolTip(QCoreApplication.translate("MainWindow", u"About Platform Base", None))
#endif // QT_CONFIG(tooltip)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.menuPanels.setTitle(QCoreApplication.translate("MainWindow", u"Panels", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"&Tools", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.mainToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Main", None))
        self.dataDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Data Panel", None))
        self.configDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Configuration", None))
        self.operationsDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Operations", None))
        self.streamingDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Streaming Controls", None))
        self.resultsDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Results", None))
    # retranslateUi

